apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq-queue-scaler.fullname" . }}
  labels:
    {{- include "rabbitmq-queue-scaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rabbitmq-queue-scaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.appConfig | toJson | sha256sum }}
      labels:
        {{- include "rabbitmq-queue-scaler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rabbitmq-queue-scaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          volumeMounts:
            - mountPath: /app/config
              name: config
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5001
            failureThreshold: 300
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 5001
            failureThreshold: 7
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5001
            failureThreshold: 7
            periodSeconds: 1
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rabbitmq-queue-scaler.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
