apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-queue-scaler.fullname" . }}
  labels:
  {{- include "rabbitmq-queue-scaler.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: http
      port: 5000
