apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streaming-service.fullname" . }}
  labels:
  {{- include "streaming-service.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{ .Values.appConfig | toYaml | nindent 4 }}
