{{ if .Values.scaling.rabbitMQ.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streaming-service.fullname" . }}-rmq-auth
data:
  host: {{ .Values.scaling.rabbitMQ.apiUrl | b64enc }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "streaming-service.fullname" . }}-auth
spec:
  secretTargetRef:
    - parameter: host
      name: {{ include "streaming-service.fullname" . }}-rmq-auth
      key: host
---
apiVersion: oleksiyp.github.io/v1
kind: ScaledObject
metadata:
  name: {{ include "streaming-service.fullname" . }}
spec:
  queueName: {{ .Values.scaling.rabbitMQ.queueName }}
  minReplicaCount: {{ .Values.scaling.rabbitMQ.minReplicaCount }}
  maxReplicaCount: {{ .Values.scaling.rabbitMQ.maxReplicaCount }}
  messageThreshold: {{ .Values.scaling.rabbitMQ.queueLengthThreshold }}
  rateThreshold: {{ .Values.scaling.rabbitMQ.messageRateThreshold }}

{{ end }}

